USE [master]
GO

/****** Object:  Database [Cofix]    Script Date: 31.03.2022 16:23:59 ******/
DROP DATABASE [Cofix]
GO

/****** Object:  Database [Cofix]    Script Date: 31.03.2022 16:23:59 ******/
CREATE DATABASE [Cofix]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cofix', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Cofix.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cofix_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Cofix_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cofix].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cofix] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cofix] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cofix] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cofix] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cofix] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cofix] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cofix] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cofix] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cofix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cofix] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cofix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cofix] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cofix] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cofix] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cofix] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cofix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cofix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cofix] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cofix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cofix] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cofix] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cofix] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cofix] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Cofix] SET  MULTI_USER 
GO

ALTER DATABASE [Cofix] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cofix] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cofix] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cofix] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Cofix] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Cofix] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Cofix] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Cofix] SET  READ_WRITE 
GO

